services:
  # バックエンド (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: kagami-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    networks:
      - kagami-network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=kagami
      - DB_USERNAME=kagami
      - DB_PASSWORD=kagami_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Webサーバー (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: kagami-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - kagami-network
    depends_on:
      - backend

  # フロントエンド (Remix)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: kagami-frontend
    restart: unless-stopped
    ports:
      - '3000:5173'
    volumes:
      - ./frontend:/app
      # - ./frontend/node_modules:/app/node_modules
    networks:
      - kagami-network
    # command: sh
    # stdin_open: true   # -i 相当
    # tty: true          # -t 相当
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://nginx:80/api

  # データベース (MariaDB)
  db:
    image: mariadb:10.5
    container_name: kagami-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=kagami
      - MYSQL_USER=kagami
      - MYSQL_PASSWORD=kagami_password
      - MYSQL_ROOT_PASSWORD=root_password
      - SERVICE_NAME=mariadb
    volumes:
      - kagami-db-data:/var/lib/mysql
    networks:
      - kagami-network

  # キャッシュ (Redis)
  redis:
    image: redis:alpine
    container_name: kagami-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - kagami-network

networks:
  kagami-network:
    driver: bridge

volumes:
  kagami-db-data:

