services:
  # バックエンド (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: sns-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    networks:
      - sns-network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sns
      - DB_USERNAME=sns
      - DB_PASSWORD=sns_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Webサーバー (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: sns-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - sns-network
    depends_on:
      - backend

  # フロントエンド (Remix)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: sns-frontend
    restart: unless-stopped
    ports:
      - '3000:5173'
    volumes:
      - ./frontend:/app
      # - ./frontend/node_modules:/app/node_modules
    networks:
      - sns-network
    command: sh
    stdin_open: true   # -i 相当
    tty: true          # -t 相当
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://nginx:80/api

  # データベース (MariaDB)
  db:
    image: mariadb:10.5
    container_name: sns-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=sns
      - MYSQL_USER=sns
      - MYSQL_PASSWORD=sns_password
      - MYSQL_ROOT_PASSWORD=root_password
      - SERVICE_NAME=mariadb
    volumes:
      - sns-db-data:/var/lib/mysql
    networks:
      - sns-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: sns-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: sns
      PMA_PASSWORD: sns_password
      PMA_PMADB: sns
    ports:
      - '8080:80'
    networks:
      - sns-network
    depends_on:
      - db

  # キャッシュ (Redis)
  redis:
    image: redis:alpine
    container_name: sns-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - sns-network

networks:
  sns-network:
    driver: bridge

volumes:
  sns-db-data:
